settings:
  legacy:
    force: false
    interval: 0s
# server:
#   status: true
#   open: false
#   port: 5002
#   host: localhost
schema:
- name: todo-list-api
  path: .
  commands:
    fmt:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    - html
    - yaml
    - yml
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
