# ローカル開発用 DockerCompose
version: '3'

services:
  app:
    container_name: "app"
    build: .
    ports:
        - "8080:8080"
    privileged: true
    ulimits:
      nproc: 65536
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      - db

  db:
    image: "mysql:5.7"
    container_name: "db"
    volumes:
      - "./docker/db/data:/var/lib/mysql"
      - "./docker/db/conf:/etc/mysql/conf.d"
    ports:
        - "3306:3306"
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    privileged: true
    ulimits:
      nproc: 65536
      nofile:
        soft: 20000
        hard: 40000

