version: '3.7'

services:
  app:
    container_name: "app"
    build:
      context: .
      target: dev
    volumes:
      - ".:/go/src/github.com/grandcolline/todo-list-api"
      # --- exclude volums ---
      - /go/src/github.com/grandcolline/todo-list-api/.docker/
      - /go/src/github.com/grandcolline/todo-list-api/.git/
    ports:
        - "8080:8080"

