// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task.proto

package pb

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	_ "github.com/golang/protobuf/ptypes/empty"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Task) Validate() error {
	return nil
}
func (this *GetTaskRequest) Validate() error {
	return nil
}
func (this *CreateTaskRequest) Validate() error {
	return nil
}
func (this *UpdateTaskRequest) Validate() error {
	return nil
}
func (this *CompleteTaskRequest) Validate() error {
	return nil
}
